-- ==========================================
-- THE CULINARY ATELIER - SUPABASE SCHEMA
-- ==========================================
-- Cara Penggunaan:
-- Copy dan Paste seluruh script ini ke dalam "SQL Editor" di Dashboard Supabase Anda,
-- lalu klik "Run" untuk membuat seluruh tabel dan relasinya secara instan.
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. EXTEND USERS TABLE (Terkait dengan auth.users bawaan Supabase)
-- Supabase menyimpan data login di auth.users, kita buat tabel profil yang nge-link ke sana
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    level INTEGER DEFAULT 1,
    xp INTEGER DEFAULT 0,
    badges JSONB DEFAULT '[]'::jsonb, -- Contoh: ["BAKER", "GRILL"]
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. RECIPES TABLE
CREATE TABLE public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- Null jika resep sistem
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL, -- e.g., 'Sarapan', 'Makan Siang'
    difficulty TEXT NOT NULL, -- e.g., 'Mudah', 'Menengah', 'Sulit'
    prep_time_minutes INTEGER NOT NULL,
    description TEXT,
    image_url TEXT,
    is_premium BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. INGREDIENTS MASTER TABLE
CREATE TABLE public.ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL, -- e.g., 'Dairy', 'Vegetables', 'Spices'
    default_unit TEXT NOT NULL -- e.g., 'gram', 'ml', 'pcs'
);

-- 4. RECIPE INGREDIENTS (Many-to-Many: Recipes <-> Ingredients)
CREATE TABLE public.recipe_ingredients (
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE CASCADE,
    ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
    amount DECIMAL NOT NULL,
    unit TEXT NOT NULL,
    PRIMARY KEY (recipe_id, ingredient_id)
);

-- 5. PANTRY ITEMS (Manajemen Dapur Pengguna)
CREATE TABLE public.pantry_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    ingredient_id BIGINT REFERENCES public.ingredients(id) ON DELETE CASCADE,
    quantity DECIMAL NOT NULL,
    status TEXT DEFAULT 'Aman', -- e.g., 'Aman', 'Menipis', 'Habis'
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, ingredient_id)
);

-- 6. BOOKMARKS (Resep Tersimpan)
CREATE TABLE public.bookmarks (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user_id, recipe_id)
);

-- 7. COMMUNITY POSTS
CREATE TABLE public.community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. COMMUNITY REPLIES
CREATE TABLE public.community_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. HISTORY LOGS (Log Aktivitas Pengguna)
CREATE TABLE public.history_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL, -- e.g., 'COOKED_RECIPE', 'EARNED_BADGE'
    meta_data JSONB DEFAULT '{}'::jsonb, -- e.g., {"recipe_id": 123, "recipe_name": "Sourdough"}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. CHAT SESSIONS (Sidebar Obrolan AI)
CREATE TABLE public.chat_sessions (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    last_active_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 11. CHAT MESSAGES
CREATE TABLE public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
    sender_role TEXT NOT NULL CHECK (sender_role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- BASIC ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================
-- Enable RLS for secure tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pantry_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.history_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- Profiles: User can read all profiles (for community), but only update their own
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Pantry: Users can only see and modify their own pantry
CREATE POLICY "Users can manage own pantry." ON public.pantry_items FOR ALL USING (auth.uid() = user_id);

-- Bookmarks: Users can only see and manage their own bookmarks
CREATE POLICY "Users can manage own bookmarks." ON public.bookmarks FOR ALL USING (auth.uid() = user_id);

-- History Logs: Users can only see their own history
CREATE POLICY "Users can view own history." ON public.history_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "System can insert history." ON public.history_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Chat: Users can only see and interact with their own chat sessions
CREATE POLICY "Users can manage own chat sessions." ON public.chat_sessions FOR ALL USING (auth.uid() = user_id);
-- Pesan chat diasumsikan aman jika session_id-nya milik user, ini disederhanakan
CREATE POLICY "Users can manage messages in own sessions." ON public.chat_messages FOR ALL USING (
    EXISTS (SELECT 1 FROM public.chat_sessions WHERE id = chat_messages.session_id AND user_id = auth.uid())
);

-- Recipes & Ingredients: Viewable by all, managed by admin/system (No RLS needed for read-only by public, or set selective RLS)
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Recipes viewable by everyone." ON public.recipes FOR SELECT USING (true);

ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Ingredients viewable by everyone." ON public.ingredients FOR SELECT USING (true);

-- Done!
